version: "3.4"
services:
  datastore:
    container_name: google-data-store
    restart: always    
    image: singularities/datastore-emulator    
    environment:
      - DATASTORE_PROJECT_ID=dummy
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081
    ports:
      - 8081:8081
    volumes:
      - ./data:/opt/data
      - ./gcloud:/root/.config/gcloud 
  datastore-ui:
    container_name: google-data-store-gui
    restart: always
    image: skarpdev/google-datastore-ui:1.0.0
    environment:
      DSUI_PROJECT_ID: dummy
      DSUI_PORT: 8000
      DSUI_DATASTORE_ENDPOINT: datastore:8081
    ports:
      - 8000:8000      
    depends_on:
      - datastore     
            
